package model.pojo;
// Generated 4.7.2014 15:10:50 by Hibernate Tools 3.6.0



/**
 * Asdf generated by hbm2java
 */
public class Asdf  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String role;

    public Asdf() {
    }

	
    public Asdf(String role) {
        this.role = role;
    }
    public Asdf(String name, String surname, String role) {
       this.name = name;
       this.surname = surname;
       this.role = role;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }




}


